# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3148ef5b295b17afb3c36d5dfeb7847e98be71803ded7e16dbd29591b112ab5bf4b87d9512ec8533f993e8833cf10595b94392a2784c35d1eb11648663884d55

test:
  secret_key_base: fd68048bc3fc002300e9aa279bdb522ce929fedfd1d799345b11e5180446863620456c83059a7b9106876b5fd332aeb8a7f76a38d190a6d735ae679284f9e9b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
